{"metadata":{"kernelspec":{"name":"python","display_name":"Pyolite","language":"python"},"language_info":{"codemirror_mode":{"name":"python","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8"},"colab":{"provenance":[]}},"nbformat_minor":0,"nbformat":4,"cells":[{"cell_type":"markdown","source":["<p style=\"text-align:center\">\n","    <a href=\"https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork1005-2022-01-01\" target=\"_blank\">\n","    <img src=\"https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png\" width=\"200\" alt=\"Skills Network Logo\"  />\n","    </a>\n","</p>\n"],"metadata":{"id":"LsRX-7AYRqMH"}},{"cell_type":"markdown","source":["# **Exception Handling**\n","\n","Estimated time needed: **15** minutes\n","    \n","\n","## Objectives\n","\n","After completing this lab you will be able to:\n","\n","* Understand exceptions    \n","* Handle the exceptions\n"],"metadata":{"id":"8TaZChZnRqMK"}},{"cell_type":"markdown","source":["## Table of Contents\n"],"metadata":{"id":"8IilD620RqMK"}},{"cell_type":"markdown","source":["* What is an Exception?\n","* Exception Handling\n"],"metadata":{"id":"w3l95WM8RqMK"}},{"cell_type":"markdown","source":["----\n"],"metadata":{"id":"SShcEsDrRqML"}},{"cell_type":"markdown","source":["## What is an Exception?\n"],"metadata":{"id":"vzJhog5GRqML"}},{"cell_type":"markdown","source":["In this section you will learn about what an exception is and see examples of them.\n"],"metadata":{"id":"URV1OF6PRqML"}},{"cell_type":"markdown","source":["### Definition\n"],"metadata":{"id":"C66X6ZutRqML"}},{"cell_type":"markdown","source":["An exception is an error that occurs during the execution of code. This error causes the code to raise an exception and if not prepared to handle it will halt the execution of the code.\n"],"metadata":{"id":"SqAJi0d1RqML"}},{"cell_type":"markdown","source":["### Examples\n"],"metadata":{"id":"j4R66RDzRqMM"}},{"cell_type":"markdown","source":["Run each piece of code and observe the exception raised\n"],"metadata":{"id":"O8ZF3bXmRqMM"}},{"cell_type":"code","source":["1/0"],"metadata":{"id":"FqINiHcnRqMM"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["<code>ZeroDivisionError</code> occurs when you try to divide by zero.\n"],"metadata":{"id":"XH3H0X1uRqMN"}},{"cell_type":"code","source":["y = a + 5"],"metadata":{"id":"UufDN5cVRqMN"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["<code>NameError</code> -- in this case, it means that you tried to use the variable a when it was not defined.\n"],"metadata":{"id":"xrsdCd5JRqMN"}},{"cell_type":"code","source":["a = [1, 2, 3]\n","a[10]"],"metadata":{"id":"lzzsFaGyRqMN"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["<code>IndexError</code> -- in this case, it occured because you tried to access data from a list using an index that does not exist for this list.\n"],"metadata":{"id":"SXP7AMAaRqMN"}},{"cell_type":"markdown","source":["There are many more exceptions that are built into Python, here is a list of them https://docs.python.org/3/library/exceptions.html\n"],"metadata":{"id":"ZMNR5WEPRqMN"}},{"cell_type":"markdown","source":["## Exception Handling\n"],"metadata":{"id":"GYzGYgxrRqMO"}},{"cell_type":"markdown","source":["In this section you will learn how to handle exceptions. You will understand how to make your program perform specified tasks instead of halting code execution when an exception is encountered.\n"],"metadata":{"id":"2dbYWRzSRqMO"}},{"cell_type":"markdown","source":["### Try Except\n"],"metadata":{"id":"Svtjn6-bRqMO"}},{"cell_type":"markdown","source":["A <code>try except</code> will allow you to execute code that might raise an exception and in the case of any exception or a specific one we can handle or catch the exception and execute specific code. This will allow us to continue the execution of our program even if there is an exception.\n","\n","Python tries to execute the code in the <code>try</code> block. In this case if there is any exception raised by the code in the <code>try</code> block, it will be caught and the code block in the <code>except</code> block will be executed. After that, the code that comes <em>after</em> the try except will be executed.\n"],"metadata":{"id":"9kQ5IrhDRqMO"}},{"cell_type":"code","source":["# potential code before try catch\n","\n","try:\n","    # code to try to execute\n","except:\n","    # code to execute if there is an exception\n","    \n","# code that will still execute if there is an exception"],"metadata":{"id":"ICQeAJNNRqMO"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["### Try Except Example\n"],"metadata":{"id":"ca1zfAx_RqMO"}},{"cell_type":"markdown","source":["In this example we are trying to divide a number given by the user, save the outcome in the variable <code>a</code>, and then we would like to print the result of the operation. When taking user input and dividing a number by it there are a couple of exceptions that can be raised. For example if we divide by zero. Try running the following block of code with <code>b</code> as a number. An exception will only be raised if <code>b</code> is zero.\n"],"metadata":{"id":"NAuASjGQRqMO"}},{"cell_type":"code","source":["a = 1\n","\n","try:\n","    b = int(input(\"Please enter a number to divide a\"))\n","    a = a/b\n","    print(\"Success a=\",a)\n","except:\n","    print(\"There was an error\")\n","        \n"],"metadata":{"id":"q3vfDjUcRqMO"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["### Try Except Specific\n"],"metadata":{"id":"VNnDde9_RqMO"}},{"cell_type":"markdown","source":["A specific <code>try except</code> allows you to catch certain exceptions and also execute certain code depending on the exception. This is useful if you do not want to deal with some exceptions and the execution should halt. It can also help you find errors in your code that you might not be aware of. Furthermore, it can help you differentiate responses to different exceptions. In this case, the code after the try except might not run depending on the error.\n"],"metadata":{"id":"a6t4zJoFRqMP"}},{"cell_type":"markdown","source":["<b>Do not run, just to illustrate:</b>\n"],"metadata":{"id":"e9eM65LXRqMP"}},{"cell_type":"code","source":["# potential code before try catch\n","\n","try:\n","    # code to try to execute\n","except (ZeroDivisionError, NameError):\n","    # code to execute if there is an exception of the given types\n","    \n","# code that will execute if there is no exception or a one that we are handling"],"metadata":{"id":"4DqlX1c4RqMP"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["# potential code before try catch\n","\n","try:\n","    # code to try to execute\n","except ZeroDivisionError:\n","    # code to execute if there is a ZeroDivisionError\n","except NameError:\n","    # code to execute if there is a NameError\n","    \n","# code that will execute if there is no exception or a one that we are handling"],"metadata":{"id":"SX--eDbRRqMP"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["You can also have an empty <code>except</code> at the end to catch an unexpected exception:\n"],"metadata":{"id":"qPvR7dkFRqMP"}},{"cell_type":"markdown","source":["<b>Do not run, just to illustrate:</b>\n"],"metadata":{"id":"IIHNaMKURqMP"}},{"cell_type":"code","source":["# potential code before try catch\n","\n","try:\n","    # code to try to execute\n","except ZeroDivisionError:\n","    # code to execute if there is a ZeroDivisionError\n","except NameError:\n","    # code to execute if there is a NameError\n","except:\n","    # code to execute if ther is any exception\n","    \n","# code that will execute if there is no exception or a one that we are handling"],"metadata":{"id":"kgrU3flTRqMP"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["### Try Except Specific Example\n"],"metadata":{"id":"GF6L4_j2RqMP"}},{"cell_type":"markdown","source":["This is the same example as above, but now we will add differentiated messages depending on the exception, letting the user know what is wrong with the input.\n"],"metadata":{"id":"f9oAqrTpRqMP"}},{"cell_type":"code","source":["a = 1\n","\n","try:\n","    b = int(input(\"Please enter a number to divide a\"))\n","    a = a/b\n","    print(\"Success a=\",a)\n","except ZeroDivisionError:\n","    print(\"The number you provided cant divide 1 because it is 0\")\n","except ValueError:\n","    print(\"You did not provide a number\")\n","except:\n","    print(\"Something went wrong\")\n","        \n"],"metadata":{"id":"jOtJulV-RqMQ"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["### Try Except Else and Finally\n"],"metadata":{"id":"aVeSFt_mRqMQ"}},{"cell_type":"markdown","source":["<code>else</code> allows one to check if there was no exception when executing the try block. This is useful when we want to execute something only if there were no errors.\n"],"metadata":{"id":"cefC0OlERqMQ"}},{"cell_type":"markdown","source":["<b>do not run, just to illustrate</b>\n"],"metadata":{"id":"APNBFVo6RqMQ"}},{"cell_type":"code","source":["# potential code before try catch\n","\n","try:\n","    # code to try to execute\n","except ZeroDivisionError:\n","    # code to execute if there is a ZeroDivisionError\n","except NameError:\n","    # code to execute if there is a NameError\n","except:\n","    # code to execute if ther is any exception\n","else:\n","    # code to execute if there is no exception\n","    \n","# code that will execute if there is no exception or a one that we are handling"],"metadata":{"id":"Df8h-yX5RqMQ"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["<code>finally</code> allows us to always execute something even if there is an exception or not. This is usually used to signify the end of the try except.\n"],"metadata":{"id":"q9g-yexmRqMQ"}},{"cell_type":"code","source":["# potential code before try catch\n","\n","try:\n","    # code to try to execute\n","except ZeroDivisionError:\n","    # code to execute if there is a ZeroDivisionError\n","except NameError:\n","    # code to execute if there is a NameError\n","except:\n","    # code to execute if other is any exception\n","else:\n","    # code to execute if there is no exception\n","finally:\n","    # code to execute at the end of the try except no matter what\n","    \n","# code that will execute if there is no exception or a one that we are handling"],"metadata":{"id":"1N2gAPiXRqMR"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["### Try Except Else and Finally Example\n"],"metadata":{"id":"JCoy36VORqMR"}},{"cell_type":"markdown","source":["You might have noticed that even if there is an error the value of <code>a</code> is always printed. Let's use the <code>else</code> and print the value of <code>a</code> only if there is no error.\n"],"metadata":{"id":"FUG9kUysRqMR"}},{"cell_type":"code","source":["a = 1\n","\n","try:\n","    b = int(input(\"Please enter a number to divide a\"))\n","    a = a/b\n","except ZeroDivisionError:\n","    print(\"The number you provided cant divide 1 because it is 0\")\n","except ValueError:\n","    print(\"You did not provide a number\")\n","except:\n","    print(\"Something went wrong\")\n","else:\n","    print(\"success a=\",a)"],"metadata":{"id":"vDkgrwYARqMR"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["Now lets let the user know that we are done processing their answer. Using the <code>finally</code>, let's add a print.\n"],"metadata":{"id":"CmlLeAmfRqMR"}},{"cell_type":"code","source":["a = 1\n","\n","try:\n","    b = int(input(\"Please enter a number to divide a\"))\n","    a = a/b\n","except ZeroDivisionError:\n","    print(\"The number you provided cant divide 1 because it is 0\")\n","except ValueError:\n","    print(\"You did not provide a number\")\n","except:\n","    print(\"Something went wrong\")\n","else:\n","    print(\"success a=\",a)\n","finally:\n","    print(\"Processing Complete\")"],"metadata":{"id":"a7OvJ44LRqMR"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["## Authors\n"],"metadata":{"id":"ltxU8D83RqMS"}},{"cell_type":"markdown","source":["<a href=\"https://www.linkedin.com/in/joseph-s-50398b136/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork1005-2022-01-01\" target=\"_blank\">Joseph Santarcangelo</a>\n"],"metadata":{"id":"AGlIGjWVRqMS"}},{"cell_type":"markdown","source":["## Change Log\n","\n","|  Date (YYYY-MM-DD) |  Version | Changed By  |  Change Description |\n","|---|---|---|---|\n","| 2020-09-02  | 2.0  | Simran | Template updates to the file|\n","|   |   |   |   |\n","|   |   |   |   |\n","\n","\n","\n","\n","## <h3 align=\"center\"> © IBM Corporation 2020. All rights reserved. <h3/>\n"],"metadata":{"id":"lSJuAUpDRqMS"}}]}